### PR TITLE
NLog ADXTarget skip retry when authentication error or permanent error

### PR DESCRIPTION
**Pull request by snakefoot**
When setting `RetryCount` for the NLog Target, then it should not retry permanent errors.

See also: https://github.com/NLog/NLog/wiki/How-to-write-a-custom-async-target ("Retry Logic" + "Batch Logic")

### CODE REVIEW

**Comment by snakefoot** [comment]
@asaharn Ready for review

**Comment by snakefoot** [comment]
@asaharn Polite poke for review

**Comment by asaharn** [comment]
LGTM
Thankyou @snakefoot.

cc @ag-ramachandran

**Review by ag-ramachandran — APPROVED** [review]

**Review by asaharn — APPROVED** [review]

**Comment by asaharn** [comment]
Thanks @snakefoot for your contribution.

**Pull request merged**
