### PR TITLE
Support for AuthenticationType = AadWorkloadIdentity

### PR DESCRIPTION
**Pull request by snakefoot**
Preview docs - https://github.com/snakefoot/azure-kusto-nlog-sink/blob/main/README.md

Kept magic value handling for `AzCliAuth` + `ManagedIdentityClientId` so non-breaking change.

### CODE REVIEW

**Comment by snakefoot** [comment]
@asaharn Ready for review

**Comment by snakefoot** [comment]
@asaharn Polite poke for review

**Comment by asaharn** [comment]
LGTM.
Thankkyou @snakefoot. 

cc @ag-ramachandran

**Review by ag-ramachandran — APPROVED** [review]

**Comment by snakefoot** [comment]
@asaharn Thank you for merging, any plans to create a release on nuget for [nlog.azure.kusto](https://www.nuget.org/packages/nlog.azure.kusto) ?

**Comment by asaharn** [comment]
Hi @snakefoot , Apologies for the delay, we currently occupied with few high priority tasks. I will start working on release the nuget asap.

**Comment by snakefoot** [comment]
Created pull-request  #18 that updates `Microsoft.Azure.Kusto.Ingest`-dependency

**Comment by asaharn** [comment]
@snakefoot Thankyou for the contribution. We have now released the Nlog v2.1.0

**Comment by snakefoot** [comment]
@asaharn The release looks great, thank you for pushing it over the finish line.

**Pull request merged**
